name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Copy frontend to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        source: "frontend/index.html"
        target: "/home/${{ secrets.USER }}/"

    - name: Deploy to Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script: |
          sudo apt update
          sudo apt install -y nginx
          sudo cp /home/${{ secrets.USER }}/index.html /var/www/html/index.html
          sudo systemctl restart nginx
